# Quebec Regions & Cities (Montreal, Quebec City, Gatineau, Sherbrooke, Saguenay, Trois-Rivieres, etc.)
QUEBEC_REGIONS = [
  {
    "regionKeywords": [
      "quebec", "qc", "montreal", "montréal", "laval", "longueuil", "terrebonne", "brossard",
      "repentigny", "saint-jerome", "saint-jérôme", "blainville", "saint-jean-sur-richelieu",
      "chateauguay", "dollard-des-ormeaux", "boucherville", "mirabel", "mascouche",
      "salaberry-de-valleyfield", "vaudreuil-dorion", "sorel-tracy", "quebec city", "québec",
      "ville de quebec", "levis", "lévis", "gatineau", "outaouais", "sherbrooke", "estrie",
      "magog", "saguenay", "chicoutimi", "jonquiere", "jonquière", "trois-rivieres", "trois-rivières",
      "shawinigan", "mauricie", "drummondville", "granby", "saint-hyacinthe", "victoriaville",
      "rimouski", "rouyn-noranda", "val-d'or"
    ],
    "stateOrProvince": "Quebec",
    "country": "Canada",
    "breweries": [
      # Montreal & Greater Montreal
      {
        "name": "Brasserie Dieu du Ciel!",
        "tagline": "World-renowned Mile End French-Canadian craft icon famed for Péché Mortel, Moralité & aphrodisiac stouts",
        "address": "29 Avenue Laurier Ouest, Montréal, QC H2T 2N2",
        "city": "Montreal",
        "state": "QC",
        "country": "Canada",
        "lat": 45.5226,
        "lng": -73.5932,
        "googleScore": 4.8,
        "googleCount": "4,200+ reviews",
        "untappdScore": 4.68,
        "untappdCount": "220k check-ins",
        "rateBeerScore": 4.75,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "1,150+ reviews",
        "beerAdvocateScore": 4.78,
        "beerAdvocateCount": "5,600+ ratings",
        "suggestedDurationMin": 85,
        "bestTimeToVisit": "3:00 PM for tap releases",
        "foodHighlights": "Artisanal saucissons, local Quebec cheese platters, gravlax, and toasted paninis.",
        "atmosphere": "Iconic bustling Mile End corner pub with vintage wooden tables, sidewalk terrace, and knowledgeable cicerones.",
        "beerHighlights": [
          { "name": "Péché Mortel", "style": "Imperial Coffee Stout (9.5% ABV)", "abv": "9.5%", "description": "Globally ranked masterpiece infused with fair-trade roasted coffee; intense mocha, dark cacao, and warming velvet." },
          { "name": "Moralité", "style": "American IPA (6.9% ABV)", "abv": "6.9%", "description": "Crisp, assertive IPA brewed with Simcoe, Citra, and Centennial hops delivering bright mango and pine." },
          { "name": "Rosée d'Hibiscus", "style": "Hibiscus Wheat Beer (5.9% ABV)", "abv": "5.9%", "description": "Ruby-pink spiced wheat ale brewed with real hibiscus flowers for gentle floral acidity and grapefruit aroma." },
          { "name": "Aphrodisiaque", "style": "Cocoa & Vanilla Stout (6.5% ABV)", "abv": "6.5%", "description": "Sensual dark stout brewed with bourbon vanilla beans and organic cocoa nibs." }
        ],
        "websiteUrl": "https://dieuduciel.com/"
      },
      {
        "name": "Messorem Bracitorium",
        "tagline": "Pointe-Saint-Charles temple of ultra-modern double dry-hopped IPAs, fruited smoothie sours & barrel-aged stouts",
        "address": "2233 Rue Pitt, Montréal, QC H4E 4H2",
        "city": "Montreal",
        "state": "QC",
        "country": "Canada",
        "lat": 45.4745,
        "lng": -73.5878,
        "googleScore": 4.9,
        "googleCount": "1,650+ reviews",
        "untappdScore": 4.72,
        "untappdCount": "110k check-ins",
        "rateBeerScore": 4.70,
        "tripAdvisorScore": 4.8,
        "tripAdvisorCount": "180+ reviews",
        "beerAdvocateScore": 4.72,
        "beerAdvocateCount": "1,850+ ratings",
        "suggestedDurationMin": 80,
        "bestTimeToVisit": "2:00 PM on sunny weekends",
        "foodHighlights": "Resident gourmet smokehouse serving smoked brisket sandwiches, pork ribs, and loaded fries.",
        "atmosphere": "Sprawling industrial beer garden along the Lachine Canal with graffiti murals, picnic tables, and chill DJ sets.",
        "beerHighlights": [
          { "name": "La Fin Du Commencement", "style": "DDH Double NEIPA (8.0% ABV)", "abv": "8.0%", "description": "Dense, opaque hop elixir saturated with Citra and Galaxy for ripe peach, candied citrus, and pillowy oat body." },
          { "name": "Petite Mort", "style": "Fruited Smoothie Sour (6.0% ABV)", "abv": "6.0%", "description": "Heavily conditioned on passionfruit, mango, and Madagascar vanilla bean." },
          { "name": "Soleil Noir", "style": "Imperial Stout (10.5% ABV)", "abv": "10.5%", "description": "Thick imperial dark ale aged on coconut flakes and roasted pecans." }
        ],
        "websiteUrl": "https://messorem.co/"
      },
      {
        "name": "Isle de Garde Brasserie",
        "tagline": "Petite-Patrie neighborhood favorite renowned for pristine Czech decoction lagers, rustic saisons & elevated bistro fare",
        "address": "1039 Rue Beaubien Est, Montréal, QC H2S 1T3",
        "city": "Montreal",
        "state": "QC",
        "country": "Canada",
        "lat": 45.5412,
        "lng": -73.5975,
        "googleScore": 4.8,
        "googleCount": "2,100+ reviews",
        "untappdScore": 4.60,
        "untappdCount": "68k check-ins",
        "rateBeerScore": 4.64,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "320+ reviews",
        "beerAdvocateScore": 4.62,
        "beerAdvocateCount": "980+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "5:30 PM for dinner pairings",
        "foodHighlights": "Artisanal grilled cheeses, crispy polenta, beef tartare, duck confit poutine, and seasonal market vegetables.",
        "atmosphere": "Warm Scandinavian-inspired wooden interior with copper tap fixtures and lush street terrace.",
        "beerHighlights": [
          { "name": "Světlý Ležák 12°", "style": "Czech Pale Lager (5.0% ABV)", "abv": "5.0%", "description": "Double-decoction mashed traditional Czech pilsner lagered 8 weeks for rich bread crust malt and crisp Saaz bitterness." },
          { "name": "Biere de Garde Ambrée", "style": "Bière de Garde (7.2% ABV)", "abv": "7.2%", "description": "Cellared Franco-Belgian farmhouse ale with caramelized malt, toasted hazelnuts, and dry earthy finish." }
        ],
        "websiteUrl": "https://isledegarde.com/"
      },
      {
        "name": "Les Insulaires Microbrasseurs",
        "tagline": "Laval’s tropical craft sanctuary pouring vibrant hazies, crisp pilsners & island-inspired gastro plates",
        "address": "275 Boul. Concorde Est, Laval, QC H7G 2E5",
        "city": "Laval",
        "state": "QC",
        "country": "Canada",
        "lat": 45.5652,
        "lng": -73.6985,
        "googleScore": 4.8,
        "googleCount": "1,150+ reviews",
        "untappdScore": 4.54,
        "untappdCount": "38k check-ins",
        "rateBeerScore": 4.50,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "140+ reviews",
        "beerAdvocateScore": 4.50,
        "beerAdvocateCount": "620+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "4:00 PM",
        "foodHighlights": "Fish tacos, smash burgers with island sauce, chicken wings, and artisanal poutine.",
        "atmosphere": "Tropical oasis taproom with indoor palm trees, neon signs, and floor-to-ceiling windows.",
        "beerHighlights": [
          { "name": "L'Île aux Singes", "style": "Hazy NEIPA (6.5% ABV)", "abv": "6.5%", "description": "Double dry-hopped with Citra, Vic Secret, and Mosaic for tropical passionfruit punch." },
          { "name": "Tahiti Pils", "style": "Crisp Pilsner (4.8% ABV)", "abv": "4.8%", "description": "Unfiltered crisp lager conditioned cold with German Hallertau hops." }
        ],
        "websiteUrl": "https://lesinsulaires.ca/"
      },
      {
        "name": "Délires et Délices Microbrasserie",
        "tagline": "Saint-Jean-sur-Richelieu craft brewery operating inside a heritage building on the Richelieu River",
        "address": "162 Rue Jacques-Cartier Nord, Saint-Jean-sur-Richelieu, QC J3B 6S8",
        "city": "Saint-Jean-sur-Richelieu",
        "state": "QC",
        "country": "Canada",
        "lat": 45.3095,
        "lng": -73.2512,
        "googleScore": 4.7,
        "googleCount": "890+ reviews",
        "untappdScore": 4.46,
        "untappdCount": "29k check-ins",
        "rateBeerScore": 4.45,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "130+ reviews",
        "beerAdvocateScore": 4.45,
        "beerAdvocateCount": "510+ ratings",
        "suggestedDurationMin": 70,
        "bestTimeToVisit": "3:00 PM for river terrace views",
        "foodHighlights": "Artisanal grilled paninis, sausages cooked in beer, charcuterie boards, and nachos.",
        "atmosphere": "Charming riverbank heritage stone pub with shaded riverside terrace and relaxed community warmth.",
        "beerHighlights": [
          { "name": "La Débordante", "style": "American IPA (6.0% ABV)", "abv": "6.0%", "description": "Generously dry-hopped with Cascade and Centennial for pine and grapefruit balance." },
          { "name": "La Noire du Richelieu", "style": "Oatmeal Stout (5.5% ABV)", "abv": "5.5%", "description": "Dark roasted malt with velvety oatmeal mouthfeel and espresso finish." }
        ],
        "websiteUrl": "https://deliresetdelices.com/"
      },

      # Quebec City & Lévis
      {
        "name": "La Barberie Microbrasserie",
        "tagline": "Quebec City’s historic cooperative microbrewery in Saint-Roch with lush green patio and innovative botanical ales",
        "address": "310 Rue Saint-Roch, Québec, QC G1K 6S2",
        "city": "Quebec City",
        "state": "QC",
        "country": "Canada",
        "lat": 46.8168,
        "lng": -71.2225,
        "googleScore": 4.7,
        "googleCount": "2,150+ reviews",
        "untappdScore": 4.52,
        "untappdCount": "78k check-ins",
        "rateBeerScore": 4.55,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "410+ reviews",
        "beerAdvocateScore": 4.50,
        "beerAdvocateCount": "1,200+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "2:30 PM for carousel flight tastings",
        "foodHighlights": "Artisanal soft pretzels, smoked salmon dip, Quebec cheeses, and BYO food policy from neighborhood restaurants.",
        "atmosphere": "Enchanting leafy beer garden terrace wrapped in climbing hops and vibrant Saint-Roch urban energy.",
        "beerHighlights": [
          { "name": "Cuivrée au Thé", "style": "Tea-Infused Amber Ale (5.0% ABV)", "abv": "5.0%", "description": "Legendary flagship brewed with real Earl Grey tea leaves for bergamot citrus and floral malt elegance." },
          { "name": "Lime & Framboise", "style": "Sour Wheat Ale (4.5% ABV)", "abv": "4.5%", "description": "Crisp kettle sour conditioned on real Quebec raspberries and lime zest." },
          { "name": "Stout Impériale Chêne & Bourbon", "style": "Barrel-Aged Stout (9.0% ABV)", "abv": "9.0%", "description": "Aged in bourbon oak barrels with rich notes of dark vanilla and toasted cocoa." }
        ],
        "websiteUrl": "https://labarberie.com/"
      },
      {
        "name": "Noctem Artisans Brasseurs",
        "tagline": "Saint-Roch pioneers of lupulin-saturated hazy IPAs, modern sours, and house-smoked charcuterie",
        "address": "438 Rue du Parvis, Québec, QC G1K 6H8",
        "city": "Quebec City",
        "state": "QC",
        "country": "Canada",
        "lat": 46.8152,
        "lng": -71.2272,
        "googleScore": 4.8,
        "googleCount": "1,850+ reviews",
        "untappdScore": 4.65,
        "untappdCount": "82k check-ins",
        "rateBeerScore": 4.66,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "280+ reviews",
        "beerAdvocateScore": 4.64,
        "beerAdvocateCount": "1,100+ ratings",
        "suggestedDurationMin": 80,
        "bestTimeToVisit": "5:00 PM for house smoked barbecue",
        "foodHighlights": "In-house smoked brisket, pulled pork sandwiches, duck wings, house beef jerky, and poutines.",
        "atmosphere": "Cozy, feline-adorned pub with dark wood accents, visible barrel room, and craft connoisseur staff.",
        "beerHighlights": [
          { "name": "Catnip", "style": "New England IPA (7.5% ABV)", "abv": "7.5%", "description": "Quebec’s iconic NEIPA champion saturated with Citra and Mosaic hops for mango, peach, and citrus juice." },
          { "name": "Herbosophie", "style": "Fruited Gose (4.8% ABV)", "abv": "4.8%", "description": "Tart wheat ale brewed with sea salt, coriander, and seasonal Quebec berry purées." }
        ],
        "websiteUrl": "https://noctem.ca/"
      },
      {
        "name": "Le Corsaire Microbrasserie",
        "tagline": "Lévis waterfront brewpub pouring traditional British-inspired cask ales overlooking Old Quebec towers",
        "address": "5955 Rue Saint-Laurent, Lévis, QC G6V 3P5",
        "city": "Lévis",
        "state": "QC",
        "country": "Canada",
        "lat": 46.8115,
        "lng": -71.1895,
        "googleScore": 4.7,
        "googleCount": "1,250+ reviews",
        "untappdScore": 4.48,
        "untappdCount": "45k check-ins",
        "rateBeerScore": 4.45,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "260+ reviews",
        "beerAdvocateScore": 4.46,
        "beerAdvocateCount": "680+ ratings",
        "suggestedDurationMin": 70,
        "bestTimeToVisit": "1:00 PM across from the ferry terminal",
        "foodHighlights": "Traditional British fish & chips, shepherd's pie, smoked brisket sandwiches, and poutine.",
        "atmosphere": "Nautical pub right on the St. Lawrence riverfront with panoramic views of Château Frontenac.",
        "beerHighlights": [
          { "name": "Davey Jones", "style": "English IPA (6.0% ABV)", "abv": "6.0%", "description": "Copper-colored classic IPA with earthy Goldings hops and rich biscuit malt balance." },
          { "name": "Brown Ale Pirate", "style": "Northern English Brown (5.2% ABV)", "abv": "5.2%", "description": "Toasted nuts, dark caramel, and gentle residual sweetness." }
        ],
        "websiteUrl": "https://lecorsaire.ca/"
      },

      # Gatineau / Outaouais
      {
        "name": "Brasserie Artisanale À la Dérive",
        "tagline": "Gatineau riverfront craft destination specializing in juicy IPAs, crisp lagers & panoramic river views",
        "address": "256 Boul. Saint-René Est, Gatineau, QC J8P 8A5",
        "city": "Gatineau",
        "state": "QC",
        "country": "Canada",
        "lat": 45.4912,
        "lng": -75.6312,
        "googleScore": 4.8,
        "googleCount": "720+ reviews",
        "untappdScore": 4.56,
        "untappdCount": "32k check-ins",
        "rateBeerScore": 4.52,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "110+ reviews",
        "beerAdvocateScore": 4.52,
        "beerAdvocateCount": "480+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "3:00 PM for patio views",
        "foodHighlights": "Wood-fired sourdough pizzas, artisanal charcuterie, grilled paninis, and gourmet poutine.",
        "atmosphere": "Modern, open-concept taproom overlooking the water with expansive sun-drenched terrace.",
        "beerHighlights": [
          { "name": "Au Gré Du Vent", "style": "Hazy NEIPA (6.5% ABV)", "abv": "6.5%", "description": "Double dry-hopped with Citra and El Dorado for candied peach, citrus, and pillowy softness." },
          { "name": "La Marée", "style": "German Pilsner (4.8% ABV)", "abv": "4.8%", "description": "Crisp, snappy, cold-lagered pilsner with noble Saaz and Tettnang hop character." }
        ],
        "websiteUrl": "https://brasseriealaderive.ca/"
      },
      {
        "name": "Les Brasseurs du Temps",
        "tagline": "Gatineau’s legendary brewery and beer museum operating in a historic 19th-century watermill along the Ruisseau de la Brasserie",
        "address": "170 Rue Montcalm, Gatineau, QC J8X 2L8",
        "city": "Gatineau",
        "state": "QC",
        "country": "Canada",
        "lat": 45.4285,
        "lng": -75.7258,
        "googleScore": 4.6,
        "googleCount": "2,850+ reviews",
        "untappdScore": 4.46,
        "untappdCount": "75k check-ins",
        "rateBeerScore": 4.48,
        "tripAdvisorScore": 4.5,
        "tripAdvisorCount": "680+ reviews",
        "beerAdvocateScore": 4.48,
        "beerAdvocateCount": "1,450+ ratings",
        "suggestedDurationMin": 80,
        "bestTimeToVisit": "12:30 PM for lunch and brewery museum tour",
        "foodHighlights": "Braised beer ribs, duck confit poutine, fish & chips, and artisanal pretzel bites with beer mustard.",
        "atmosphere": "Historic stone watermill with working waterwheel, multi-level terraces, and integrated Quebec brewing history museum.",
        "beerHighlights": [
          { "name": "Candiose", "style": "Belgian Tripel (8.5% ABV)", "abv": "8.5%", "description": "Strong golden ale brewed with Belgian candy sugar, coriander, and fruity abbey yeast." },
          { "name": "Trois Portages", "style": "White IPA (6.0% ABV)", "abv": "6.0%", "description": "Hybrid wheat ale hopped assertively with American hops and spiced with orange peel." }
        ],
        "websiteUrl": "https://brasseursdutemps.com/"
      },

      # Sherbrooke & Eastern Townships (Magog, Orford)
      {
        "name": "Siboire Dépôt",
        "tagline": "Iconic Sherbrooke train-station brewpub famous for Trip d’Automne, fresh cask ales & wood-fired pizza",
        "address": "80 Rue du Dépôt, Sherbrooke, QC J1H 5G1",
        "city": "Sherbrooke",
        "state": "QC",
        "country": "Canada",
        "lat": 45.4012,
        "lng": -71.8872,
        "googleScore": 4.8,
        "googleCount": "2,850+ reviews",
        "untappdScore": 4.45,
        "untappdCount": "110k check-ins",
        "rateBeerScore": 4.5,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "1,050+ reviews",
        "beerAdvocateScore": 4.46,
        "beerAdvocateCount": "1,920+ ratings",
        "suggestedDurationMin": 85,
        "bestTimeToVisit": "12:30 PM",
        "foodHighlights": "Famous house wood-fired sourdough pizzas, fresh Atlantic fish & chips, artisanal duck wings, and local curd poutine.",
        "atmosphere": "Historic 1890s railway station transformed into a soaring wood-beamed brewpub with sunlit trackside terrace and bicycle racks.",
        "beerHighlights": [
          { "name": "Trip d’Automne", "style": "American IPA (6.5% ABV)", "abv": "6.5%", "description": "Flagship amber IPA featuring bold pine, grapefruit resin, and balanced biscuit malt complexity." },
          { "name": "Commander", "style": "Double IPA (8.2% ABV)", "abv": "8.2%", "description": "Lush tropical notes of mango and candied orange peel with an assertive bitter finish." }
        ],
        "websiteUrl": "https://siboire.ca/"
      },
      {
        "name": "Microbrasserie La Memphré",
        "tagline": "Magog lakeside brewpub pouring award-winning craft ales with stunning Lake Memphremagog views",
        "address": "12 Rue Merry Sud, Magog, QC J1X 3K9",
        "city": "Magog",
        "state": "QC",
        "country": "Canada",
        "lat": 45.2675,
        "lng": -72.1512,
        "googleScore": 4.7,
        "googleCount": "1,450+ reviews",
        "untappdScore": 4.48,
        "untappdCount": "42k check-ins",
        "rateBeerScore": 4.46,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "480+ reviews",
        "beerAdvocateScore": 4.46,
        "beerAdvocateCount": "720+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "2:00 PM",
        "foodHighlights": "Duck burgers, fish & chips, locally crafted sausages, and gourmet poutine.",
        "atmosphere": "Charming lakeside pub with expansive outdoor patio overlooking the river mouth and lake.",
        "beerHighlights": [
          { "name": "Memphré IPA", "style": "American IPA (6.2% ABV)", "abv": "6.2%", "description": "Crisp citrus and pine IPA brewed with Cascade and Centennial hops." },
          { "name": "La Magogoise", "style": "Belgian Blonde (5.5% ABV)", "abv": "5.5%", "description": "Easy-drinking golden ale with subtle clove and fruit yeast notes." }
        ],
        "websiteUrl": "https://lamemphre.com/"
      },

      # Saguenay (Chicoutimi, Jonquière)
      {
        "name": "Microbrasserie La Voie Maltée",
        "tagline": "Saguenay’s pioneer microbrewery in Chicoutimi famous for beer cuisine and malty creations",
        "address": "777 Boul. Talbot, Chicoutimi, QC G7H 4B5",
        "city": "Saguenay",
        "state": "QC",
        "country": "Canada",
        "lat": 48.4112,
        "lng": -71.0612,
        "googleScore": 4.7,
        "googleCount": "1,980+ reviews",
        "untappdScore": 4.50,
        "untappdCount": "62k check-ins",
        "rateBeerScore": 4.50,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "580+ reviews",
        "beerAdvocateScore": 4.48,
        "beerAdvocateCount": "1,120+ ratings",
        "suggestedDurationMin": 80,
        "bestTimeToVisit": "1:00 PM for beer-infused dining",
        "foodHighlights": "Famous 'bière et bouffe' menu: beer-braised meats, malt-crusted poutines, and gourmet burgers.",
        "atmosphere": "Warm, cavernous pub with dark wood booths, copper accents, and lively Saguenay hospitality.",
        "beerHighlights": [
          { "name": "La Malédiction", "style": "Milk Stout (5.5% ABV)", "abv": "5.5%", "description": "Award-winning sweet stout brewed with lactose and dark roasted malts for cocoa and cream flavors." },
          { "name": "L'Échappée", "style": "American IPA (6.0% ABV)", "abv": "6.0%", "description": "Balanced, aromatic IPA with citrus peel and resinous pine." }
        ],
        "websiteUrl": "https://lavoiemaltee.com/"
      },

      # Trois-Rivières & Shawinigan
      {
        "name": "Le Trou du Diable Microbrasserie",
        "tagline": "World-famous Mauricie craft titan in Shawinigan famed for oak-aged sours, Saison du Tracteur & La Butteuse",
        "address": "412 Avenue Willow, Shawinigan, QC G9N 1X2",
        "city": "Shawinigan",
        "state": "QC",
        "country": "Canada",
        "lat": 46.5412,
        "lng": -72.7512,
        "googleScore": 4.8,
        "googleCount": "2,450+ reviews",
        "untappdScore": 4.66,
        "untappdCount": "145k check-ins",
        "rateBeerScore": 4.72,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "620+ reviews",
        "beerAdvocateScore": 4.70,
        "beerAdvocateCount": "3,400+ ratings",
        "suggestedDurationMin": 85,
        "bestTimeToVisit": "1:30 PM",
        "foodHighlights": "Local terroir cuisine, duck burgers, wild boar sausages, and artisanal poutine.",
        "atmosphere": "Historic Saint-Maurice River industrial taproom adorned with eclectic folk art and gleaming copper tanks.",
        "beerHighlights": [
          { "name": "Saison du Tracteur", "style": "Farmhouse Saison (6.0% ABV)", "abv": "6.0%", "description": "Globally acclaimed dry, citrusy, spicy farmhouse ale double dry-hopped with aromatic hops." },
          { "name": "La Butteuse", "style": "Belgian Tripel (10.0% ABV)", "abv": "10.0%", "description": "Rich golden ale with pear, apple, and warming alcoholic complexity." }
        ],
        "websiteUrl": "https://troududiable.com/"
      },
      {
        "name": "Microbrasserie Le Temps d'une Pinte",
        "tagline": "Downtown Trois-Rivières cooperative worker-owned brewpub marrying craft ales with specialty roasted coffee",
        "address": "1465 Rue Notre-Dame Centre, Trois-Rivières, QC G9A 4X4",
        "city": "Trois-Rivières",
        "state": "QC",
        "country": "Canada",
        "lat": 46.3425,
        "lng": -72.5412,
        "googleScore": 4.8,
        "googleCount": "1,650+ reviews",
        "untappdScore": 4.54,
        "untappdCount": "48k check-ins",
        "rateBeerScore": 4.52,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "390+ reviews",
        "beerAdvocateScore": 4.52,
        "beerAdvocateCount": "820+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "12:00 PM for lunch bistro pairings",
        "foodHighlights": "Gourmet scotch eggs, smoked salmon tartare, house duck poutine, and artisan coffee desserts.",
        "atmosphere": "Industrial-chic brick bistro with copper brewing vessels and bustling downtown street terrace.",
        "beerHighlights": [
          { "name": "La Sainte-Bavarde", "style": "Belgian Blonde Ale (6.2% ABV)", "abv": "6.2%", "description": "Crisp Belgian-style blonde ale with balanced yeast spice and floral hops." },
          { "name": "Café-Torréfacteur", "style": "Coffee Porter (5.5% ABV)", "abv": "5.5%", "description": "Conditioned on fresh in-house roasted espresso beans with dark chocolate notes." }
        ],
        "websiteUrl": "https://letempsdunepinte.ca/"
      },

      # Drummondville
      {
        "name": "Le BockAle Microbrasserie",
        "tagline": "Drummondville craft brewery renowned for creative IPAs, dark stouts & pioneering craft non-alcoholic ales",
        "address": "2330 Rue Saint-Pierre, Drummondville, QC J2C 5A5",
        "city": "Drummondville",
        "state": "QC",
        "country": "Canada",
        "lat": 45.8912,
        "lng": -72.5112,
        "googleScore": 4.7,
        "googleCount": "750+ reviews",
        "untappdScore": 4.50,
        "untappdCount": "32k check-ins",
        "rateBeerScore": 4.46,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "95+ reviews",
        "beerAdvocateScore": 4.46,
        "beerAdvocateCount": "480+ ratings",
        "suggestedDurationMin": 70,
        "bestTimeToVisit": "3:00 PM",
        "foodHighlights": "Artisan smash burgers, nachos, local cheese curds, and warm soft pretzels.",
        "atmosphere": "Modern industrial tasting room with neon accents and views into the brewhouse.",
        "beerHighlights": [
          { "name": "L'Or Frappé", "style": "New England IPA (6.5% ABV)", "abv": "6.5%", "description": "Double dry-hopped with Citra and Mosaic for ripe tropical punch." },
          { "name": "Trouble-Fête", "style": "Berliner Weisse (4.2% ABV)", "abv": "4.2%", "description": "Tart, refreshing sour wheat ale with crisp lemon acidity." }
        ],
        "websiteUrl": "https://lebockale.com/"
      },

      # Granby
      {
        "name": "Microbrasserie Le Grimoire",
        "tagline": "Granby craft brewing pioneer famous for Desérables maple beer, Vie de Château & cozy pub atmosphere",
        "address": "285 Rue Principale, Granby, QC J2G 2W2",
        "city": "Granby",
        "state": "QC",
        "country": "Canada",
        "lat": 45.4015,
        "lng": -72.7312,
        "googleScore": 4.7,
        "googleCount": "950+ reviews",
        "untappdScore": 4.46,
        "untappdCount": "36k check-ins",
        "rateBeerScore": 4.44,
        "tripAdvisorScore": 4.5,
        "tripAdvisorCount": "190+ reviews",
        "beerAdvocateScore": 4.44,
        "beerAdvocateCount": "540+ ratings",
        "suggestedDurationMin": 70,
        "bestTimeToVisit": "4:00 PM",
        "foodHighlights": "Beer-marinated ribs, gourmet poutines, artisan burgers, and warm pretzels.",
        "atmosphere": "Whimsical spellbook-themed historic tavern with dark woodwork and warm brick fireplace.",
        "beerHighlights": [
          { "name": "Desérables", "style": "Maple Amber Ale (5.5% ABV)", "abv": "5.5%", "description": "Brewed with 100% pure Quebec maple syrup for delicate woody sweetness and caramel malt finish." },
          { "name": "Vie de Château", "style": "Oak-Aged Barleywine (10.0% ABV)", "abv": "10.0%", "description": "Rich dark fruits, toffee, and bourbon oak complexity." }
        ],
        "websiteUrl": "https://legrimoire.ca/"
      },

      # Saint-Hyacinthe
      {
        "name": "Le Bilboquet Microbrasserie",
        "tagline": "Saint-Hyacinthe craft brewing cornerstone founded in 1990, famed for La Corriveau, Coup de Canon & Belgian ales",
        "address": "1850 Rue des Cascades, Saint-Hyacinthe, QC J2S 3J3",
        "city": "Saint-Hyacinthe",
        "state": "QC",
        "country": "Canada",
        "lat": 45.6275,
        "lng": -72.9465,
        "googleScore": 4.7,
        "googleCount": "1,120+ reviews",
        "untappdScore": 4.48,
        "untappdCount": "45k check-ins",
        "rateBeerScore": 4.48,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "210+ reviews",
        "beerAdvocateScore": 4.48,
        "beerAdvocateCount": "780+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "2:30 PM",
        "foodHighlights": "Artisanal grilled cheeses, duck sausages, cheese platters, and local poutines.",
        "atmosphere": "Classic European brewpub aesthetic with dark wood, stained glass, and friendly neighborhood patrons.",
        "beerHighlights": [
          { "name": "La Corriveau", "style": "Oatmeal Stout (5.5% ABV)", "abv": "5.5%", "description": "Canada’s legendary benchmark oatmeal stout; silky smooth dark chocolate and roasted coffee." },
          { "name": "Coup de Canon", "style": "Belgian Strong Dark (9.0% ABV)", "abv": "9.0%", "description": "Intense dried fruit, plum, and caramel malt fermented with authentic abbey yeast." }
        ],
        "websiteUrl": "https://lebilboquet.qc.ca/"
      },

      # Victoriaville
      {
        "name": "L'Hermite Microbrasserie",
        "tagline": "Victoriaville craft brewery pouring creative IPAs and lagers in a relaxed, friendly taproom",
        "address": "196 Rue Notre-Dame Est, Victoriaville, QC G6P 3Z6",
        "city": "Victoriaville",
        "state": "QC",
        "country": "Canada",
        "lat": 46.0592,
        "lng": -71.9565,
        "googleScore": 4.7,
        "googleCount": "680+ reviews",
        "untappdScore": 4.48,
        "untappdCount": "26k check-ins",
        "rateBeerScore": 4.45,
        "tripAdvisorScore": 4.6,
        "tripAdvisorCount": "110+ reviews",
        "beerAdvocateScore": 4.46,
        "beerAdvocateCount": "410+ ratings",
        "suggestedDurationMin": 70,
        "bestTimeToVisit": "3:30 PM",
        "foodHighlights": "Gourmet smash burgers, loaded nachos, and poutine made with fresh local cheese curds.",
        "atmosphere": "Airy brick pub with board games, community tables, and sunny street patio.",
        "beerHighlights": [
          { "name": "La Trotteuse", "style": "American IPA (6.0% ABV)", "abv": "6.0%", "description": "Bright citrus, mango, and pine hop balance with clean dry finish." },
          { "name": "Le Solitaire", "style": "Crisp Pilsner (4.8% ABV)", "abv": "4.8%", "description": "Clean, refreshing lager with German Hallertau hops." }
        ],
        "websiteUrl": "https://lhermite.ca/"
      },

      # Rimouski
      {
        "name": "Le Bien, le Malt",
        "tagline": "Historic Rimouski craft brewpub celebrating English cask traditions, St. Lawrence terroir & local hospitality",
        "address": "141 Avenue de la Cathédrale, Rimouski, QC G5L 5H8",
        "city": "Rimouski",
        "state": "QC",
        "country": "Canada",
        "lat": 48.4485,
        "lng": -68.5285,
        "googleScore": 4.8,
        "googleCount": "1,120+ reviews",
        "untappdScore": 4.54,
        "untappdCount": "34k check-ins",
        "rateBeerScore": 4.50,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "240+ reviews",
        "beerAdvocateScore": 4.50,
        "beerAdvocateCount": "610+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "4:00 PM for cask ale tappings",
        "foodHighlights": "Local maritime smoked fish platters, gourmet meat pies, and artisan Quebec cheese boards.",
        "atmosphere": "Cozy wood-paneled maritime pub with warm low lighting, board games, and friendly coastal conversation.",
        "beerHighlights": [
          { "name": "La Mousson", "style": "English IPA (5.8% ABV)", "abv": "5.8%", "description": "Traditional cask-conditioned IPA with earthy Fuggle and Golding hops." },
          { "name": "L'Orée du Bois", "style": "Scotch Ale (7.5% ABV)", "abv": "7.5%", "description": "Rich peat malt complexity with toffee and caramel depth." }
        ],
        "websiteUrl": "https://lebienlemalt.com/"
      },

      # Rouyn-Noranda & Val-d'Or
      {
        "name": "Le Trèfle Noir Microbrasserie",
        "tagline": "Abitibi-Témiscamingue craft pioneer in Rouyn-Noranda pouring award-winning stouts and wild sours",
        "address": "145 Rue Principale, Rouyn-Noranda, QC J9X 4P3",
        "city": "Rouyn-Noranda",
        "state": "QC",
        "country": "Canada",
        "lat": 48.2412,
        "lng": -79.0215,
        "googleScore": 4.8,
        "googleCount": "980+ reviews",
        "untappdScore": 4.56,
        "untappdCount": "38k check-ins",
        "rateBeerScore": 4.52,
        "tripAdvisorScore": 4.7,
        "tripAdvisorCount": "190+ reviews",
        "beerAdvocateScore": 4.52,
        "beerAdvocateCount": "580+ ratings",
        "suggestedDurationMin": 75,
        "bestTimeToVisit": "5:00 PM",
        "foodHighlights": "Smoked meat sandwiches, craft nachos, artisanal sausages, and northern poutine.",
        "atmosphere": "Welcoming northern brewpub with warm rustic timber decor and friendly craft beer community.",
        "beerHighlights": [
          { "name": "La Trèfle Noir Stout", "style": "Dry Irish Stout (4.8% ABV)", "abv": "4.8%", "description": "Silky dark ale with notes of espresso and dark chocolate." },
          { "name": "L'Appel du Large", "style": "American IPA (6.5% ABV)", "abv": "6.5%", "description": "Juicy citrus and resinous pine hop punch." }
        ],
        "websiteUrl": "https://letreflenoir.com/"
      }
    ],
    "hotels": [
      {
        "name": "Hôtel William Gray (Old Montreal)",
        "type": "hotel",
        "priceCategory": "over_200",
        "estimatedPricePerNight": "$260 CAD / night",
        "address": "421 Rue Saint-Vincent, Montréal, QC H2Y 3A6",
        "city": "Montreal",
        "state": "QC",
        "lat": 45.5075,
        "lng": -73.5532,
        "description": "Historic luxury boutique hotel in Old Montreal with rooftop terrace and spa.",
        "amenities": ["Rooftop Terrace", "Full Spa", "Valet Parking", "Fitness Center", "Free Wi-Fi"],
        "bookingSearchUrl": "https://www.google.com/travel/hotels/s/Hotel+William+Gray+Montreal"
      },
      {
        "name": "Hôtel PUR Québec (Saint-Roch)",
        "type": "hotel",
        "priceCategory": "100_to_200",
        "estimatedPricePerNight": "$175 CAD / night",
        "address": "395 Rue de la Couronne, Québec, QC G1K 7X4",
        "city": "Quebec City",
        "state": "QC",
        "lat": 46.8155,
        "lng": -71.2285,
        "description": "Chic urban hotel in Saint-Roch, 2 minutes walk from Noctem and La Barberie.",
        "amenities": ["Indoor Heated Pool", "Sauna", "Fitness Center", "Restaurant & Bar"],
        "bookingSearchUrl": "https://www.google.com/travel/hotels/s/Hotel+PUR+Quebec"
      }
    ],
    "airbnbs": [
      {
        "name": "Plateau & Mile End Brewery Loft",
        "type": "airbnb",
        "priceCategory": "100_to_200",
        "estimatedPricePerNight": "$145 CAD / night",
        "address": "Avenue Laurier Ouest, Montréal, QC H2T 2N2",
        "city": "Montreal",
        "state": "QC",
        "lat": 45.5228,
        "lng": -73.5935,
        "description": "Sunlit exposed brick apartment directly across from Brasserie Dieu du Ciel! in the heart of Mile End.",
        "amenities": ["Full Kitchen", "High-Speed Wi-Fi", "Balcony", "Espresso Machine"],
        "bookingSearchUrl": "https://www.google.com/travel/hotels/s/Montreal+Mile+End+Airbnb"
      }
    ]
  }
]
