#!/usr/bin/env python3
"""
Full updater for:
- src/data/worldCitiesData.ts
- src/data/locationSuggestions.ts
- src/data/verifiedRealBreweries.ts
- src/data/verifiedCanadianBreweries.ts
"""
import json
import re

# =========================================================================
# 1. NEW CITIES FOR worldCitiesData.ts
# =========================================================================
VT_CITIES = [
    {
        "name": "Burlington, VT, USA",
        "cityName": "Burlington",
        "asciiname": "Burlington",
        "subtext": "Chittenden County, Vermont • Pop. 44,743",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 44743,
        "lat": 44.4759,
        "lng": -73.2121,
        "altNames": ["BTV", "Queen City"],
        "craftBeerHubRank": "Top Craft State Capital"
    },
    {
        "name": "South Burlington, VT, USA",
        "cityName": "South Burlington",
        "asciiname": "South Burlington",
        "subtext": "Chittenden County, Vermont • Pop. 20,292",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 20292,
        "lat": 44.4670,
        "lng": -73.1709,
        "altNames": ["S Burlington"],
        "craftBeerHubRank": "Lake Champlain Metro"
    },
    {
        "name": "Essex, VT, USA",
        "cityName": "Essex",
        "asciiname": "Essex",
        "subtext": "Chittenden County, Vermont • Pop. 22,094",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 22094,
        "lat": 44.5256,
        "lng": -73.1118,
        "altNames": ["Essex Junction"],
        "craftBeerHubRank": None
    },
    {
        "name": "Colchester, VT, USA",
        "cityName": "Colchester",
        "asciiname": "Colchester",
        "subtext": "Chittenden County, Vermont • Pop. 17,524",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 17524,
        "lat": 44.5439,
        "lng": -73.1485,
        "altNames": ["Malletts Bay"],
        "craftBeerHubRank": None
    },
    {
        "name": "Rutland, VT, USA",
        "cityName": "Rutland",
        "asciiname": "Rutland",
        "subtext": "Rutland County, Vermont • Pop. 15,807",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 15807,
        "lat": 43.6106,
        "lng": -72.9726,
        "altNames": ["Marble City"],
        "craftBeerHubRank": "Green Mountains Hub"
    },
    {
        "name": "Bennington, VT, USA",
        "cityName": "Bennington",
        "asciiname": "Bennington",
        "subtext": "Bennington County, Vermont • Pop. 15,333",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 15333,
        "lat": 42.8781,
        "lng": -73.1968,
        "altNames": ["Battle of Bennington"],
        "craftBeerHubRank": "Southern VT Gateway"
    },
    {
        "name": "Brattleboro, VT, USA",
        "cityName": "Brattleboro",
        "asciiname": "Brattleboro",
        "subtext": "Windham County, Vermont • Pop. 12,184 (Area > 28,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 12184,
        "lat": 42.8509,
        "lng": -72.5579,
        "altNames": ["Connecticut River Valley"],
        "craftBeerHubRank": "Artisanal Beer Hub"
    },
    {
        "name": "Hartford, VT, USA",
        "cityName": "Hartford",
        "asciiname": "Hartford",
        "subtext": "Windsor County, Vermont • Pop. 10,686 (Upper Valley > 75,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10686,
        "lat": 43.6534,
        "lng": -72.3787,
        "altNames": ["White River Junction", "WRJ", "Upper Valley"],
        "craftBeerHubRank": "Upper Valley Craft"
    },
    {
        "name": "Barre, VT, USA",
        "cityName": "Barre",
        "asciiname": "Barre",
        "subtext": "Washington County, Vermont • Pop. 17,200",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 17200,
        "lat": 44.1970,
        "lng": -72.5020,
        "altNames": ["Granite City"],
        "craftBeerHubRank": None
    },
    {
        "name": "Montpelier, VT, USA",
        "cityName": "Montpelier",
        "asciiname": "Montpelier",
        "subtext": "Washington County, Vermont • Pop. 8,074 (Metro > 59,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 8074,
        "lat": 44.2601,
        "lng": -72.5754,
        "altNames": ["State Capital"],
        "craftBeerHubRank": "Capital Craft Scene"
    },
    {
        "name": "Milton, VT, USA",
        "cityName": "Milton",
        "asciiname": "Milton",
        "subtext": "Chittenden County, Vermont • Pop. 10,723 (Area > 210,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10723,
        "lat": 44.6367,
        "lng": -73.1107,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Williston, VT, USA",
        "cityName": "Williston",
        "asciiname": "Williston",
        "subtext": "Chittenden County, Vermont • Pop. 10,103 (Area > 210,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10103,
        "lat": 44.4367,
        "lng": -73.0696,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Middlebury, VT, USA",
        "cityName": "Middlebury",
        "asciiname": "Middlebury",
        "subtext": "Addison County, Vermont • Pop. 9,152 (Area > 37,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 9152,
        "lat": 44.0153,
        "lng": -73.1673,
        "altNames": ["Addison Craft Trail"],
        "craftBeerHubRank": "Otter Creek Valley"
    },
    {
        "name": "St. Albans, VT, USA",
        "cityName": "St. Albans",
        "asciiname": "St. Albans",
        "subtext": "Franklin County, Vermont • Pop. 13,800 (Area > 49,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 13800,
        "lat": 44.8109,
        "lng": -73.0832,
        "altNames": ["Saint Albans", "Rail City"],
        "craftBeerHubRank": "Northern Lake Champlain"
    },
    {
        "name": "Stowe, VT, USA",
        "cityName": "Stowe",
        "asciiname": "Stowe",
        "subtext": "Lamoille County, Vermont • Pop. 5,223 (Area > 80,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 5223,
        "lat": 44.4654,
        "lng": -72.6874,
        "altNames": ["Stowe Mountain"],
        "craftBeerHubRank": "Heady Topper Mecca"
    },
    {
        "name": "Waterbury, VT, USA",
        "cityName": "Waterbury",
        "asciiname": "Waterbury",
        "subtext": "Washington County, Vermont • Pop. 5,331 (Area > 100,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 5331,
        "lat": 44.3378,
        "lng": -72.7562,
        "altNames": ["Crossroads of Vermont"],
        "craftBeerHubRank": "IPA Crossroads"
    },
    {
        "name": "St. Johnsbury, VT, USA",
        "cityName": "St. Johnsbury",
        "asciiname": "St. Johnsbury",
        "subtext": "Caledonia County, Vermont • Pop. 7,364 (Area > 31,000)",
        "type": "city",
        "stateOrProvince": "Vermont",
        "code": "VT",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 7364,
        "lat": 44.4192,
        "lng": -72.0165,
        "altNames": ["Saint Johnsbury", "Northeast Kingdom"],
        "craftBeerHubRank": "NEK Trail Gateway"
    }
]

QC_CITIES = [
    {
        "name": "Beloeil, QC, Canada",
        "cityName": "Beloeil",
        "asciiname": "Beloeil",
        "subtext": "La Vallée-du-Richelieu, Quebec • Pop. 22,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 22500,
        "lat": 45.5667,
        "lng": -73.2000,
        "altNames": ["Mont-Saint-Hilaire Metro"],
        "craftBeerHubRank": None
    },
    {
        "name": "Mont-Saint-Hilaire, QC, Canada",
        "cityName": "Mont-Saint-Hilaire",
        "asciiname": "Mont-Saint-Hilaire",
        "subtext": "La Vallée-du-Richelieu, Quebec • Pop. 19,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 19000,
        "lat": 45.5620,
        "lng": -73.1910,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Lambert, QC, Canada",
        "cityName": "Saint-Lambert",
        "asciiname": "Saint-Lambert",
        "subtext": "Montérégie, Quebec • Pop. 22,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 22000,
        "lat": 45.5000,
        "lng": -73.5167,
        "altNames": ["St-Lambert"],
        "craftBeerHubRank": None
    },
    {
        "name": "Sainte-Thérèse, QC, Canada",
        "cityName": "Sainte-Thérèse",
        "asciiname": "Sainte-Therese",
        "subtext": "Thérèse-De Blainville, Quebec • Pop. 26,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 26500,
        "lat": 45.6333,
        "lng": -73.8500,
        "altNames": ["Ste-Therese", "Sainte Therese"],
        "craftBeerHubRank": None
    },
    {
        "name": "Deux-Montagnes, QC, Canada",
        "cityName": "Deux-Montagnes",
        "asciiname": "Deux-Montagnes",
        "subtext": "Deux-Montagnes, Quebec • Pop. 18,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 18000,
        "lat": 45.5333,
        "lng": -73.8833,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Candiac, QC, Canada",
        "cityName": "Candiac",
        "asciiname": "Candiac",
        "subtext": "Roussillon, Quebec • Pop. 21,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 21000,
        "lat": 45.3833,
        "lng": -73.5167,
        "altNames": ["South Shore"],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Constant, QC, Canada",
        "cityName": "Saint-Constant",
        "asciiname": "Saint-Constant",
        "subtext": "Roussillon, Quebec • Pop. 29,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 29000,
        "lat": 45.3667,
        "lng": -73.5667,
        "altNames": ["St-Constant"],
        "craftBeerHubRank": None
    },
    {
        "name": "Sainte-Catherine, QC, Canada",
        "cityName": "Sainte-Catherine",
        "asciiname": "Sainte-Catherine",
        "subtext": "Roussillon, Quebec • Pop. 17,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 17500,
        "lat": 45.4000,
        "lng": -73.5833,
        "altNames": ["Ste-Catherine"],
        "craftBeerHubRank": None
    },
    {
        "name": "La Prairie, QC, Canada",
        "cityName": "La Prairie",
        "asciiname": "La Prairie",
        "subtext": "Roussillon, Quebec • Pop. 26,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 26500,
        "lat": 45.4167,
        "lng": -73.5000,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Varennes, QC, Canada",
        "cityName": "Varennes",
        "asciiname": "Varennes",
        "subtext": "Marguerite-D'Youville, Quebec • Pop. 21,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 21500,
        "lat": 45.6833,
        "lng": -73.4333,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Lazare, QC, Canada",
        "cityName": "Saint-Lazare",
        "asciiname": "Saint-Lazare",
        "subtext": "Vaudreuil-Soulanges, Quebec • Pop. 22,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 22000,
        "lat": 45.4000,
        "lng": -74.1333,
        "altNames": ["St-Lazare"],
        "craftBeerHubRank": None
    },
    {
        "name": "Pincourt, QC, Canada",
        "cityName": "Pincourt",
        "asciiname": "Pincourt",
        "subtext": "Vaudreuil-Soulanges, Quebec • Pop. 15,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 15500,
        "lat": 45.3833,
        "lng": -73.9833,
        "altNames": ["Île Perrot"],
        "craftBeerHubRank": None
    },
    {
        "name": "L'Assomption, QC, Canada",
        "cityName": "L'Assomption",
        "asciiname": "L'Assomption",
        "subtext": "Lanaudière, Quebec • Pop. 22,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 22500,
        "lat": 45.8333,
        "lng": -73.4167,
        "altNames": ["Assomption"],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Lin-Laurentides, QC, Canada",
        "cityName": "Saint-Lin-Laurentides",
        "asciiname": "Saint-Lin-Laurentides",
        "subtext": "Montcalm, Quebec • Pop. 24,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 24000,
        "lat": 45.8500,
        "lng": -73.7500,
        "altNames": ["Saint-Lin"],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Colomban, QC, Canada",
        "cityName": "Saint-Colomban",
        "asciiname": "Saint-Colomban",
        "subtext": "La Rivière-du-Nord, Quebec • Pop. 17,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 17500,
        "lat": 45.7333,
        "lng": -74.1333,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Sainte-Marthe-sur-le-Lac, QC, Canada",
        "cityName": "Sainte-Marthe-sur-le-Lac",
        "asciiname": "Sainte-Marthe-sur-le-Lac",
        "subtext": "Deux-Montagnes, Quebec • Pop. 19,500",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 19500,
        "lat": 45.5333,
        "lng": -73.9333,
        "altNames": ["Ste-Marthe-sur-le-Lac"],
        "craftBeerHubRank": None
    },
    {
        "name": "Saint-Basile-le-Grand, QC, Canada",
        "cityName": "Saint-Basile-le-Grand",
        "asciiname": "Saint-Basile-le-Grand",
        "subtext": "La Vallée-du-Richelieu, Quebec • Pop. 17,000",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 17000,
        "lat": 45.5333,
        "lng": -73.2833,
        "altNames": ["St-Basile"],
        "craftBeerHubRank": None
    },
    {
        "name": "Sainte-Agathe-des-Monts, QC, Canada",
        "cityName": "Sainte-Agathe-des-Monts",
        "asciiname": "Sainte-Agathe-des-Monts",
        "subtext": "Les Laurentides, Quebec • Pop. 11,000 (Area > 45,000)",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 11000,
        "lat": 46.0460,
        "lng": -74.2810,
        "altNames": ["Sainte-Agathe", "Ste-Agathe-des-Monts"],
        "craftBeerHubRank": "Laurentians Craft Gateway"
    },
    {
        "name": "Mont-Tremblant, QC, Canada",
        "cityName": "Mont-Tremblant",
        "asciiname": "Mont-Tremblant",
        "subtext": "Les Laurentides, Quebec • Pop. 10,000 (Area > 40,000)",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 10000,
        "lat": 46.1167,
        "lng": -74.6000,
        "altNames": ["Tremblant"],
        "craftBeerHubRank": "Alpine Craft Haven"
    },
    {
        "name": "Matane, QC, Canada",
        "cityName": "Matane",
        "asciiname": "Matane",
        "subtext": "La Matanie, Quebec • Pop. 14,000 (Area > 25,000)",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 14000,
        "lat": 48.8500,
        "lng": -67.5333,
        "altNames": ["Gaspésie Gateway"],
        "craftBeerHubRank": "St. Lawrence Craft Port"
    },
    {
        "name": "Amos, QC, Canada",
        "cityName": "Amos",
        "asciiname": "Amos",
        "subtext": "Abitibi, Quebec • Pop. 12,500 (Area > 25,000)",
        "type": "city",
        "stateOrProvince": "Quebec",
        "code": "QC",
        "country": "Canada",
        "countryCode": "CA",
        "countryName": "Canada",
        "population": 12500,
        "lat": 48.5667,
        "lng": -78.1167,
        "altNames": [],
        "craftBeerHubRank": "Abitibi Brewing"
    }
]

# NEW YORK STATE CITIES (>15k total for 50km radius area, strictly excluding wider NYC metro small cities)
# For NYC metro: only New York City is included!
NY_CITIES = [
    {
        "name": "Rome, NY, USA",
        "cityName": "Rome",
        "asciiname": "Rome",
        "subtext": "Oneida County, New York • Pop. 32,125",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 32125,
        "lat": 43.2128,
        "lng": -75.4557,
        "altNames": ["Copper City"],
        "craftBeerHubRank": None
    },
    {
        "name": "North Tonawanda, NY, USA",
        "cityName": "North Tonawanda",
        "asciiname": "North Tonawanda",
        "subtext": "Niagara County, New York • Pop. 30,496",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 30496,
        "lat": 43.0381,
        "lng": -78.8642,
        "altNames": ["Lumber City"],
        "craftBeerHubRank": None
    },
    {
        "name": "Lockport, NY, USA",
        "cityName": "Lockport",
        "asciiname": "Lockport",
        "subtext": "Niagara County, New York • Pop. 20,876",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 20876,
        "lat": 43.1706,
        "lng": -78.6903,
        "altNames": ["Erie Canal Locks"],
        "craftBeerHubRank": None
    },
    {
        "name": "Geneva, NY, USA",
        "cityName": "Geneva",
        "asciiname": "Geneva",
        "subtext": "Ontario County, New York • Pop. 12,800 (Area > 80,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 12800,
        "lat": 42.8687,
        "lng": -76.9777,
        "altNames": ["Seneca Lake"],
        "craftBeerHubRank": "Finger Lakes Heart"
    },
    {
        "name": "Olean, NY, USA",
        "cityName": "Olean",
        "asciiname": "Olean",
        "subtext": "Cattaraugus County, New York • Pop. 13,400 (Area > 50,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 13400,
        "lat": 42.0776,
        "lng": -78.4297,
        "altNames": ["Enchanted Mountains"],
        "craftBeerHubRank": None
    },
    {
        "name": "Dunkirk, NY, USA",
        "cityName": "Dunkirk",
        "asciiname": "Dunkirk",
        "subtext": "Chautauqua County, New York • Pop. 12,500 (Area > 70,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 12500,
        "lat": 42.4795,
        "lng": -79.3339,
        "altNames": ["Lake Erie Trail"],
        "craftBeerHubRank": None
    },
    {
        "name": "Fredonia, NY, USA",
        "cityName": "Fredonia",
        "asciiname": "Fredonia",
        "subtext": "Chautauqua County, New York • Pop. 10,500 (Area > 70,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10500,
        "lat": 42.4401,
        "lng": -79.3317,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Canandaigua, NY, USA",
        "cityName": "Canandaigua",
        "asciiname": "Canandaigua",
        "subtext": "Ontario County, New York • Pop. 10,500 (Area > 150,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10500,
        "lat": 42.8876,
        "lng": -77.2819,
        "altNames": ["Chosen Spot", "Canandaigua Lake"],
        "craftBeerHubRank": "FLX Craft Gateway"
    },
    {
        "name": "Corning, NY, USA",
        "cityName": "Corning",
        "asciiname": "Corning",
        "subtext": "Steuben County, New York • Pop. 10,600 (Area > 90,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10600,
        "lat": 42.1428,
        "lng": -77.0547,
        "altNames": ["Crystal City", "Market Street"],
        "craftBeerHubRank": "Southern Tier Craft"
    },
    {
        "name": "Fulton, NY, USA",
        "cityName": "Fulton",
        "asciiname": "Fulton",
        "subtext": "Oswego County, New York • Pop. 11,400 (Area > 120,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 11400,
        "lat": 43.3223,
        "lng": -76.4172,
        "altNames": ["Oswego River"],
        "craftBeerHubRank": None
    },
    {
        "name": "Massena, NY, USA",
        "cityName": "Massena",
        "asciiname": "Massena",
        "subtext": "St. Lawrence County, New York • Pop. 10,150 (Area > 35,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10150,
        "lat": 44.9281,
        "lng": -74.8927,
        "altNames": ["St. Lawrence Seaway"],
        "craftBeerHubRank": None
    },
    {
        "name": "Ogdensburg, NY, USA",
        "cityName": "Ogdensburg",
        "asciiname": "Ogdensburg",
        "subtext": "St. Lawrence County, New York • Pop. 10,000 (Area > 30,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 10000,
        "lat": 44.6942,
        "lng": -75.4866,
        "altNames": [],
        "craftBeerHubRank": None
    },
    {
        "name": "Cooperstown, NY, USA",
        "cityName": "Cooperstown",
        "asciiname": "Cooperstown",
        "subtext": "Otsego County, New York • Pop. 1,800 (Area > 50,000)",
        "type": "city",
        "stateOrProvince": "New York",
        "code": "NY",
        "country": "USA",
        "countryCode": "US",
        "countryName": "United States",
        "population": 1800,
        "lat": 42.7006,
        "lng": -74.9243,
        "altNames": ["Baseball Hall of Fame", "Otsego Lake"],
        "craftBeerHubRank": "Belgian Farmhouse Mecca (Ommegang)"
    }
]

# Update worldCitiesData.ts
print("Reading src/data/worldCitiesData.ts...")
with open("src/data/worldCitiesData.ts", "r") as f:
    wcd_text = f.read()

# Collect names already in worldCitiesData.ts
existing_names = set(re.findall(r'"name":\s*"([^"]+)"', wcd_text))
cities_to_add = []
for c in VT_CITIES + QC_CITIES + NY_CITIES:
    if c["name"] not in existing_names:
        cities_to_add.append(c)

print(f"Adding {len(cities_to_add)} cities to worldCitiesData.ts...")
if cities_to_add:
    # Find the closing "];"
    insert_pos = wcd_text.rfind("];")
    if insert_pos != -1:
        formatted_cities = ",\n" + ",\n".join(json.dumps(c, indent=2) for c in cities_to_add)
        new_wcd_text = wcd_text[:insert_pos].rstrip().rstrip(",") + formatted_cities + "\n];\n"
        with open("src/data/worldCitiesData.ts", "w") as f:
            f.write(new_wcd_text)
        print("Updated src/data/worldCitiesData.ts successfully.")

print("Step 1 done.")
